ACR v1.1 - Refactor and Improved Masking
GSTT-CSC/hazen pull request #343
Opened 2023-05-11 11:02 UTC by YassineAzma

This PR introduces the ACRTools class in acr_tools.py, which contains a number of useful functions that are frequently used throughout the ACR analysis scripts.

**sort_images** = DICOM and image sorting via the image position

**determine_rotation** = Estimate the rotation angle of the phantom using the Hough circle detector

**rotate_images** = Rotates the images by the rotation angle

**mask_image** = Thresholds the image - if the intensity variation in the image is sufficiently large, local thresholding methods are used rather than a global intensity threshold.

**find_phantom_center** = Now decoupled from the masking routine. The image is blurred and the edges are then sharpened along the diagonal. The Hough circle detector is then used to identify the phantom using prior knowledge of its geometry.

**circular_mask** = Draw a circular mask

**measure_orthogonal_lengths** = Measure the horizontal and vertical extent of the mask.

**rotate_point** = Find x' and y' for a point rotated around a given centre by a given angle.

**find_n_highest_peaks** = Given an array, report the location and intensity of the highest peaks.

Along with other general improvements, these functions have been used to refactor the existing ACR functions. This will prevent unneeded repetition in the unit tests for the individual analysis scripts by grouping tests for reused functions in the acr_tools.py module.

**NOTE**: All ACR test outputs have changed by <2% owing to changes in the masking and centre definition methods. These changes should make them more robust to issues seen in Issues #333 and #332.

Pending: Complete unit tests for acr_tools module.

Resolves #333, #332

2023-05-11 11:06 UTC, YassineAzma commented
@Lucrezia-Cester I can't seem to find where the test_tools.py unit tests are called in the workflow tests. Could you please point me in the right direction to do something for my test_acr_tools?

2023-07-17 15:39 UTC, tomaroberts requested changes
@YassineAzma – this is an amazing PR frankly. Crazy amount of work gone into this. Apologies it's taken us so long to review. Thank you so much for doing it! 🎉🎉🎉 

I've run the unit tests locally and they are all passing.

I've also run `hazen acr_XXX` one-by-one on each of the ACR Tasks. They all work on the Siemens test dataset you've provided and they all provide output report files.

A couple of minor things I've spotted:
- There is a 'rotation angle' message printed during the `acr_spatial_resolution` task. I think there is an error with the wording which needs fixing. See here: <img width="939" alt="image" src="https://github.com/GSTT-CSC/hazen/assets/15610752/28826bb8-fa8a-4502-8497-c70e95a5158b">
- During the `acr_snr` task, there is a matplotlib related message printed. See below. Can you suppress this if possible to keep the output clean. <img width="1258" alt="Screenshot 2023-07-17 at 16 33 50" src="https://github.com/GSTT-CSC/hazen/assets/15610752/b035a5d3-82eb-472a-a1fc-1c9fb0228ad8">
- In the `test_geometric_accurary` and `test_acr_uniformity` files, there are commented lines referring to Philips unit tests. Is this a reminder for the future? If so, perhaps just adjust to "TODO" which is a special type of comment for this kind of purpose.

Again, this amazing. Thank you!

2023-07-17 15:42 UTC, tomaroberts commented
Just to add to this, you've written a fair amount of documentation in the files, which is great. When we come to fully uplifting the hazen ReadTheDocs, we'll definitely need your input on making the guidance as clear as possible. Thanks.

2023-07-28 12:11 UTC, tomaroberts approved these changes

2023-07-28 12:13 UTC, merged

2023-09-15 11:00 UTC, sophie22 commented on hazenlib/tasks/acr_geometric_accuracy.py
> +        mask = self.ACR_obj.mask_image(self.ACR_obj.images[6])
Is it meant to be images[6] or the pixel array of the DICOM input to this function?