397 standardise docstrings
GSTT-CSC/hazen pull request #398
Opened 2024-01-02 10:23 UTC by sophie22

2024-01-05 00:05 UTC, sophie22 commented
All functions in MagNet task scripts have at least a placeholder docstring in the Google format.

2024-01-16 13:42 UTC, sophie22 commented
All functions in ACR task scripts have at least a placeholder docstrings in the Google format.

2024-01-16 14:24 UTC, sophie22 commented
All functions in ACR task scripts have at least a placeholder docstring in the Google format.

2024-01-16 18:54 UTC, tomaroberts requested changes
Great start on getting these docstrings filled out.

Just a few comments.

PR is still in draft btw, if you want to undraft it.

2024-01-16 18:54 UTC, tomaroberts commented on hazenlib/ACRObject.py
> +        # print(z)
Some old testing/comments which can be removed.

2024-01-16 18:54 UTC, tomaroberts commented on hazenlib/tasks/acr_spatial_resolution.py
> +        """Fit sigmoid function to erf?
Suggest just calling this "Fit ERF" for now if unclear.

2024-01-16 18:54 UTC, tomaroberts commented on hazenlib/tasks/acr_spatial_resolution.py
> +            """Some more magic maths
Given this will be potentially released, can you change this to something generic.

2024-01-16 18:54 UTC, tomaroberts commented on hazenlib/tasks/spatial_resolution.py
> +        """Locate Hugh Circles in a DICOM pixel array
tiny typo: "Hough Circles"

2024-01-16 18:54 UTC, tomaroberts commented on tests/test_ghosting.py
> +        #     )
Is this test supposed to be commented out?

2024-01-17 15:19 UTC, sophie22 commented on hazenlib/ACRObject.py
> +        # print(z)
addressed by adding a TODO for future development

2024-01-17 15:20 UTC, sophie22 commented on hazenlib/tasks/acr_spatial_resolution.py
> +        """Fit sigmoid function to erf?
done

2024-01-17 15:20 UTC, sophie22 commented on hazenlib/tasks/acr_spatial_resolution.py
> +            """Some more magic maths
done

2024-01-17 15:21 UTC, sophie22 commented on hazenlib/tasks/spatial_resolution.py
> +        """Locate Hugh Circles in a DICOM pixel array
corrected

2024-01-17 15:41 UTC, sophie22 commented on tests/test_ghosting.py
> +        #     )
removed the ones that are no longer relevant

2024-01-17 17:06 UTC, tomaroberts commented on tests/test_ghosting.py
> -
Did you intend to remove these?

2024-01-17 17:08 UTC, tomaroberts approved these changes

2024-01-17 17:09 UTC, merged

2024-01-17 17:09 UTC, sophie22 commented
pls don't delete the branch