Address python version compatibility
GSTT-CSC/hazen pull request #422
Opened 2024-03-05 14:02 UTC by sophie22

Tested on Mac with Python 3.11.5 and on Windows via Anaconda with Python 3.11.7

2024-03-05 16:22 UTC, sophie22 commented
ModuleNotFoundError: No module named 'distutils' - removed since Python 3.12, deprecated since Python 3.10

2024-03-18 15:35 UTC, tomaroberts requested changes
Couple of comments, mainly around the Windows requirements file.

2024-03-18 15:35 UTC, tomaroberts commented on README.md
I don't think we need to flag these. Prefer to to just keep the README clean.

2024-03-18 15:35 UTC, tomaroberts commented on requirements_Win3.11.txt
What is the issue with the standard requirements.txt on Windows?

This one is enormous. There are a lot of unnecessary packages included, such as Jupyter and probably many more. Can this be shortened to just the necessary packages, like the standard one?

The PR says tested with Anaconda – have you tried it with pip on Windows?

2024-03-22 18:18 UTC, sophie22 commented on requirements_Win3.11.txt
Beatriz used pip on Windows and worked well for her. I tested with Anaconda because an issue was raised around that in particular, but turned out to be not version related.
Deleted this file for simplicity.

2024-04-02 12:21 UTC, tomaroberts approved these changes

2024-04-02 12:22 UTC, merged